import type { GetServerSideProps } from "next";
import Head from "next/head";
import { createServerSideClient } from "~/lib/supabase-server";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex min-h-screen max-w-screen-md flex-col items-center justify-center bg-background">
        <h1 className="mb-4 text-5xl font-bold">Welcome</h1>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const supabase = createServerSideClient({ req: ctx.req, res: ctx.res });

  const { data, error } = await supabase.auth.getUser();

  if (error || !data.user) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};
